title: 张星海的个人博客-星博客-前端开发
description: 张星海的文档,专注前端技术总结,记录生活点滴,网站建设,个人博客搭建,曾经的大连,未来的武汉,分享朴素、实用的前端技术
version: 1.0.0
port: 4001
# host: 0.0.0.0

## collections_dir: group
collections:
  patterns:
    title: 设计模式
    sort_by: sort
    output: true
  opengl:
    title: OpenGL Learning Plan
    sort_by: sort
    output: true
  articles:
    title: 观点
    sort_by: date
    output: true
  tlogs:
    title: 日记
    sort_by: sort
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  path: /feed.xml

# gitment:
#   enable: true
#   mint: true # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
#   count: true # Show comments count in post meta area
#   lazy: false # Comments lazy loading with a button
#   cleanly: false # Hide 'Powered by ...' on footer, and more
#   # language: # Force language, or auto switch by theme
#   github_user: zxh19890103
#   github_repo: git@github.com:zxh19890103/singhi.io.git
#   client_id: 8f12af399879a21edfb4
#   client_secret: 89caf3baee7c9962dddc6f6fa3c8db0825c51f1f
#   # proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
#   # redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled

exclude:
  - tools
  - node_modules
  - scripts
  - package.json
  - yarn.lock
